name: Trigger auto deployment for container-app-zki746tt7vu5a

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-zki746tt7vu5a-AutoDeployTrigger-466102a3-0fc6-4da0-8523-233fdcdf0175.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPZKI746TT7VU5A_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPZKI746TT7VU5A_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPZKI746TT7VU5A_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPZKI746TT7VU5A_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPZKI746TT7VU5A_REGISTRY_PASSWORD }}
          containerAppName: container-app-zki746tt7vu5a
          resourceGroup: expresssamplebb78b7b9
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


